- name: variables in ansible
  hosts: mongodb
  # this is play level variables, map
  vars:
    COURSE: DevOps with AWS
    TRAINER: Sivakumar
    DURATION: 110hrs
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, i am learing Ansible"
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello, i am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"

