- name: variables from inventory
  hosts: mongodb
  tasks:
  - name: print mongodb username
    ansible.buitin.degub:
     msg: "username is: {{MONGO_USERNAME}}"



- name: variables from inventory
  hosts: mongodb
  tasks:
  - name: print mongodb username
    ansible.builtin.debug:
     msg: "username is: {{MONGO_USERNAME}}"