- name: install multiple packages
  hosts: localhost
  tasks:
  - name: install package
    ansible.builtin.yum:
     name: "{{item}}"
     state: installed
    loop:
    - nginx
    - mongodb
    - ansible
    - postfix
    - mysql