- name: install multiple packages
  hosts: mongodb
  become: yes 
  tasks:
  - name: install package
    ansible.builtin.yum:
     name: "{{item}}"
     state: installed
     # this is list of strings
    loop:
    - nginx
    - ansible
    - postfix
    - mysql