- name: install multiple packages
  hosts: mongod
  become: yes 
  tasks:
  - name: install package
    ansible.builtin.yum:
     name: "{{item}}"
     state: installed
    loop:
    - nginx
    - ansible
    - postfix
    - mysql